a = bytes(5)
b = int(5)
c = float(5.0)
d = chr(5)
e = str("5")
f = bool(True)
g = list([1, 2, 3])
h = tuple((1, 2, 3))
i = set({1, 2, 3})
j = dict({"one": 1, "two": 2, "three": 3})
print("Data types:")
print("a is of type:", type(a))
print("b is of type:", type(b))
print("c is of type:", type(c))
print("d is of type:", type(d))
print("e is of type:", type(e))
print("f is of type:", type(f))
print("g is of type:", type(g))
print("h is of type:", type(h))
print("i is of type:", type(i))
print("j is of type:", type(j))
